services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api:ro
    environment:
      SWAGGER_JSON: https://stoplight.io/open-source/prism

  prism:
    image: stoplight/prism:4
    container_name: "prism"
    ports:
      - "8081:4010"
    volumes:
      - ./api:/api:ro
    command: 'mock -h 0.0.0.0 /api/openapi.yaml'
