services:
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: "swagger-ui"
    ports:
      - "8080:8080"
    volumes:
      - ./api:/api
    environment:
      SWAGGER_JSON: /api/openapi.yaml
